In [69]:
import pandas as pd
df=pd.read_csv("C:\\Users\\hp\\Data Science With AI\\web_scraping_project\\amazon_laptops4.csv")

In [70]:
df.head()

,title,price,rating,brand,ram,storage,color,processor
0,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",NaN,HP,16GB,512GB,Silver,Apple M365
1,"Dell 15 SmartChoice (Previously Inspiron), Int...","72,990",NaN,Dell,16GB,1TB,Silver,Intel
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",NaN,Lenovo,8GB,512GB,Silver,AMD
3,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...","42,990",Pure Silver,Acer,8GB,256GB,Silver,Apple A114
4,"Dell 15 (Previously Inspiron), R5-7520U Proces...","53,990",NaN,Dell,8GB,512GB,Black,NaN

In [71]:
# TO CHECK ROW AND COLUMNS
df.shape

(800, 8)

In [72]:
# CHECk columns NAMES
df.columns

Index(['title', 'price', 'rating', 'brand', 'ram', 'storage', 'color',
       'processor'],
      dtype='str')

In [73]:
# step 2 check basic Information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      800 non-null    str
 1   price      794 non-null    str
 2   rating     32 non-null     str
 3   brand      800 non-null    str
 4   ram        689 non-null    str
 5   storage    664 non-null    str
 6   color      626 non-null    str
 7   processor  635 non-null    str
dtypes: str(8)
memory usage: 50.1 KB

In [74]:
# check missing values in the dataset
df.isnull().sum()

title          0
price          6
rating       768
brand          0
ram          111
storage      136
color        174
processor    165
dtype: int64

In [75]:
# clean the price column
df["price"].dtype

In [76]:
df["price"].head()

0    69,990
1    72,990
2    44,999
3    42,990
4    53,990
Name: price, dtype: str

In [77]:
df["price"].unique()

<StringArray>
[  '69,990',   '72,990',   '44,999',   '42,990',   '53,990',   '87,990',
   '67,990',   '73,990', '5,89,990',   '35,990',
 ...
   '64,810', '3,67,900',   '64,900', '1,67,490',   '27,490',   '83,465',
   '47,990',   '43,699',   '57,490',   '62,490']
Length: 218, dtype: str

In [78]:
df["price"] = df["price"].str.replace(",","")

In [79]:
df["price"]=pd.to_numeric(df["price"],errors="coerce")

In [80]:
df["price"]=df["price"].fillna(df["price"].mean())

In [81]:
df["price"].dtype

dtype('float64')

In [82]:
df["price"].isnull().sum()

np.int64(0)

In [83]:
# Now i want to clean rating columns

In [84]:
df["rating"].unique()

<StringArray>
[                              nan,                     'Pure Silver',
                          'Silver',                      'Steel Gray',
                   'Get it faster',          'Silver RYZEN 7-7th Gen',
                            'Blue',                    'Carbon Black',
      'Cloud Grey - Ryzen 5 5500U',                     'Cool Silver',
                   'Silver MSO'24',                      'Quiet Blue',
                     'Mixed Black', 'Dark Shadow Gray - RTX 3050 6GB',
    'Luna Grey|16GB | 512GB | 14"',              'Silver-13th Gen i5']
Length: 16, dtype: str

In [85]:
df.isnull().sum()

title          0
price          0
rating       768
brand          0
ram          111
storage      136
color        174
processor    165
dtype: int64

In [86]:
df["rating"].value_counts()

rating
Get it faster                      9
Silver                             6
Blue                               2
Cool Silver                        2
Quiet Blue                         2
Dark Shadow Gray - RTX 3050 6GB    2
Pure Silver                        1
Steel Gray                         1
Silver RYZEN 7-7th Gen             1
Carbon Black                       1
Cloud Grey - Ryzen 5 5500U         1
Silver MSO'24                      1
Mixed Black                        1
Luna Grey|16GB | 512GB | 14"       1
Silver-13th Gen i5                 1
Name: count, dtype: int64

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      292 non-null    str
 1   price      289 non-null    float64
 2   rating     9 non-null      str
 3   brand      292 non-null    str
 4   ram        263 non-null    str
 5   storage    244 non-null    str
 6   color      254 non-null    str
 7   processor  260 non-null    str
dtypes: float64(1), str(7)
memory usage: 18.4 KB

In [46]:
df["rating"].unique()

<StringArray>
[                          nan,               'Get it faster',
                      'Silver',                'Carbon Black',
                  'Quiet Blue',                 'Cool Silver',
 'Luna Grey {Core-5-24GB Ram}']
Length: 7, dtype: str

In [47]:
df["rating"].value_counts(dropna=False)

rating
NaN                            283
Get it faster                    4
Silver                           1
Carbon Black                     1
Quiet Blue                       1
Cool Silver                      1
Luna Grey {Core-5-24GB Ram}      1
Name: count, dtype: int64

In [48]:
df["rating"].isna().sum()

np.int64(283)

In [49]:
# Then we can decide whether to keep those 7 missing values, remove them, or fill them.
df["rating"].describe()

count                 9
unique                6
top       Get it faster
freq                  4
Name: rating, dtype: object

In [62]:
# df["rating"] = df["rating"].fillna(df["rating"].isna().mean() * 100)
df["rating"].isna().sum()

np.int64(283)

In [64]:
df["rating"]=pd.to_numeric(df["rating"], errors='coerce')

In [65]:
df["rating"] = df["rating"].fillna(df["rating"].median())

In [67]:
df["rating"].isna().sum()

np.int64(292)

In [68]:
df["rating"].value_counts(dropna=False)

rating
NaN    292
Name: count, dtype: int64

In [53]:
df["brand"].unique()

<StringArray>
[     'ASUS',        'HP',    'Lenovo',      'Dell',      'Acer',   'Samsung',
   'Unknown',     'Apple',      'acer',       'MSI',      'DELL', 'Primebook',
   'MaxBook']
Length: 13, dtype: str

In [ ]:
df["brand"].isnull().sum()

np.int64(0)

In [ ]:
df["brand"]=df["brand"].replace("acer","Acer")

In [ ]:
df["brand"].dtype

In [ ]:
df["ram"].unique()

<StringArray>
['16GB', '24GB', '8GB', '36GB', 'RAM', '48GB', '32GB']
Length: 7, dtype: str

In [ ]:
df["rating"].unique()

array([3.2, 4.6, 4.8, 4.7, 3.6, 3.9, 2.4, 3.8, 4.5, 5. , 4.3, 4.1, 2. ,
       2.8, 4. , 4.2, 3.3])

In [ ]:
df["ram"].unique()

<StringArray>
['16GB', '24GB', '8GB', '36GB', 'RAM', '48GB', '32GB']
Length: 7, dtype: str

In [ ]:
df["ram"] = df["ram"].str.extract(r"(\d+)").astype(float)

In [ ]:
import numpy as np

df["ram"] = df["ram"].replace("RAM", np.nan)

In [ ]:
df["ram"].unique()

array([16., 24.,  8., 36., nan, 48., 32.])

In [ ]:
df["ram"] = df["ram"].fillna(df["ram"].median())

In [ ]:
df["ram"].unique()

array([16., 24.,  8., 36., 48., 32.])

In [ ]:
df.isna().sum()

title          0
price          0
rating         0
brand          0
ram            0
storage        3
color        153
processor    458
dtype: int64

In [ ]:
df["ram"].dtype

dtype('float64')

In [ ]:
df["storage"].unique()

<StringArray>
['512GB', '2TB', '1TB', nan, '256GB']
Length: 5, dtype: str

In [ ]:
def convert_storage(x):
    if pd.isna(x):
        return x
    if "TB" in x:
        return float(x.replace("TB", "")) * 1024
    return float(x.replace("GB", ""))

df["storage"] = df["storage"].apply(convert_storage)

In [ ]:
df["storage"].unique()

array([ 512., 2048., 1024.,   nan,  256.])

In [ ]:
df["storage"].isna().sum()

np.int64(3)

In [ ]:
df[df["storage"].isna()]

,title,price,rating,brand,ram,storage,color,processor
3,"Acer Aspire 3 Laptop A325-42 | 15.6"" (39.6 cm)...",40999,4.7,Acer,8.0,NaN,Gray,AMD
539,"ASUS Vivobook 15 (2026),Intel Core 5 320 (Seri...",101990,4.7,ASUS,16.0,NaN,Blue,Intel
694,"ASUS Vivobook 15 (2026),Intel Core 5 320 (Seri...",101990,4.7,ASUS,16.0,NaN,Blue,Intel

In [ ]:
df.loc[[3, 539, 694], "title"]

3      Acer Aspire 3 Laptop A325-42 | 15.6" (39.6 cm)...
539    ASUS Vivobook 15 (2026),Intel Core 5 320 (Seri...
694    ASUS Vivobook 15 (2026),Intel Core 5 320 (Seri...
Name: title, dtype: str

In [ ]:
df["storage"] = df["storage"].fillna(df["storage"].median())

In [ ]:
df["storage"].unique()

array([ 512., 2048., 1024.,  256.])

In [ ]:
df["storage"].dtype

dtype('float64')

In [ ]:
# clean the color
df["color"].unique()

<StringArray>
['Silver', nan, 'Gray', 'Black', 'Blue', 'Grey', 'Indigo']
Length: 7, dtype: str

In [ ]:
import random

apple_colors = ["Sky Blue", "Silver", "Starlight", "Midnight"]

for i in df.index:
    if df.loc[i, "brand"] == "Apple" and pd.isna(df.loc[i, "color"]):
        df.loc[i, "color"] = random.choice(apple_colors)

In [ ]:
df["color"].unique()

<StringArray>
[   'Silver', 'Starlight',      'Gray',  'Sky Blue',     'Black',      'Blue',
  'Midnight',      'Grey',    'Indigo',         nan]
Length: 10, dtype: str

In [ ]:
df["color"].value_counts(dropna=False)

color
Silver       376
Black        134
Starlight     39
Blue          39
Midnight      37
Sky Blue      35
Grey          19
Indigo        11
Gray           3
NaN            3
Name: count, dtype: int64

In [ ]:
df[df["color"].isna()]

,title,price,rating,brand,ram,storage,color,processor
452,Lenovo ThinkPad E14 AMD Ryzen 7 7735HS (16GB R...,97990,2.8,Lenovo,16.0,512.0,NaN,AMD
467,Lenovo ThinkPad E14 AMD Ryzen 7 7735HS (16GB R...,97990,2.8,Lenovo,16.0,512.0,NaN,AMD
591,"ASUS Vivobook 15 (2026),Intel Core 3 304 (Seri...",74990,4.7,ASUS,8.0,512.0,NaN,Intel

In [ ]:
df["color"]=df["color"].fillna("Black")

In [ ]:
df[df["color"].isna()]

Empty DataFrame
Columns: [title, price, rating, brand, ram, storage, color, processor]
Index: []

In [ ]:
df["color"].unique()

<StringArray>
[   'Silver', 'Starlight',      'Gray',  'Sky Blue',     'Black',      'Blue',
  'Midnight',      'Grey',    'Indigo']
Length: 9, dtype: str

In [ ]:
df["processor"].unique()

<StringArray>
['Snapdragon', nan, 'AMD', 'Intel']
Length: 4, dtype: str

In [ ]:
df["processor"].value_counts(dropna=False)

processor
NaN           458
Snapdragon    108
Intel         108
AMD            22
Name: count, dtype: int64

               price
count     292.000000
mean   107715.269896
std    118450.574361
min     19990.000000
25%     49990.000000
50%     69990.000000
75%     83490.000000
max    589990.000000

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      292 non-null    str
 1   price      292 non-null    float64
 2   rating     9 non-null      str
 3   brand      292 non-null    str
 4   ram        263 non-null    str
 5   storage    244 non-null    str
 6   color      254 non-null    str
 7   processor  260 non-null    str
dtypes: float64(1), str(7)
memory usage: 18.4 KB